### ISSUE TITLE
CLI exit codes

### ISSUE THREAD

**Issue by savchenko** [taskchampion/taskchampion#217]
As per https://github.com/taskchampion/taskchampion/pull/212#discussion_r621458155, `ta` should use meaningful return codes. Current list under proposal:

- `0` No errors, normal exit.
- `1` Generic error.
- `2` Never used to avoid conflicts with Bash.
- `3` Unable to execute with the given parameters.
- `4` I/O error.
- `5` Database error.

**Comment by djmitche** [comment]
@savchenko what does "Database error" mean in this context?

**Comment by djmitche** [comment]
I'm a little vague on the reasoning here -- particularly about 4 and 5.  3 makes sense, as it's basically a CLI syntax error, but I need more detail on the last two.

**Comment by savchenko** [comment]
> what does "Database error" mean in this context?

One that happens within an application layer where underlying cause isn't I/O error returned by a lower-level component.

Failed `fopen()` would be an I/O error, while `SQLITE_CORRUPT` belongs to the database.

### I/O error
- Unable to update config file
- Can't read/write local SQLite file due to permission error
- GC process is interrupted mid-way due to FS error (handle/inode has disappeared, etc)
- ...

### Database error
- Is is Friday 13th and `sync-server` has returned code 666; application is confused.
- `sync-server` has returned something that can't be deciphered.
- Working set / replica / log are corrupted
- SQLite schema has changed in an unexpected way
- ...

**Comment by dbr** [comment]
`DatabaseError` could be used in the SQLite storage if there is an error executing one of the queries (say if the database gets manually modified and someone drops one of the columns or whatever).

https://github.com/dbr/taskchampion/blob/ff894f6ff634a9dc5d6d2b7511c258d4c0e8d102/taskchampion/src/storage/sqlite.rs#L79-L93

Currently these all get wrapped in `anyhow::Result` for convenience, but it would be quite reasonable to have these return in `Result<..., SqliteError>` instead

`IoError` could be used if, say, the config file fails to open due to bad file permissions etc

*That said*, I'm not sure I agree with these as exit codes. This level of error seems like a useful distinctions to have in the API (e.g to give helpful error messages in an alternative UI), but I'm not sure they are too useful as exit codes (i.e I think they could all map to exit code 1)

The reason is if someone is writing a script wrapping TC, I can't imagine why the shell script would care if the command failed because of an unparsable error versus a IO error. Most likely it just needs to exit with exit-code-1 and the message on stderr would explain why (e.g the config has no read-permissions, the SQLite database is corrupt, etc)

Instead, I can imagine it being useful to have more specific exit codes to some commands - as a (maybe bad) example:

1. `task delete --help`, the non-parseable `task delete @#$%^&*(`, broken DB, etc exit with generic exit code of 1
2. `task delete 23` exits with 0 on success
3. Rerunning `task delete 23` then exits with exit code 3 because task 23 isn't present in the working set

Similarly things like `task sync` it might be useful to have "generic error" for most things, "IO error"  for network errors where retrying might succeed

I suspect it's better to add these specific error codes as needed rather than trying to foresee all the cases which could be useful - since "non-zero exit code indicates a failure", it's quite safe to selectively add specific exit codes in future

**Comment by savchenko** [comment]
> errors where retrying might succeed

Which is "any error". Someone might run `fsck`, restore from a backup, etc.

> I suspect it's better to add these specific error codes as needed rather than trying to foresee all the cases which could be useful

Fair point. Shall we settle with `0`, `1` and `3` then?

**Comment by dbr** [comment]
> > errors where retrying might succeed
>
> Which is "any error". Someone might run fsck, restore from a backup, etc.

Technically true, but I mean within the context of a writing a script around taskchampion - e.g if someone writes a script which syncs every 5 minutes, it's quite reasonable they might want to, say, know if there was a network drop out, automatically retry and only log an error if it happens x times. It would be a little impractical/unwise to handle an IO error by launching `sudo fsck` in such a script (thus I can't think of a good reason to have a CLI exit code specifically for IO errors)

> Fair point. Shall we settle with 0, 1 and 3 then?

I'd say just 0 and 1 for now, unless there's a specific reason having non-parseable arguments needs a separate code?

**Comment by savchenko** [comment]
> I'd say just 0 and 1 for now, unless there's a specific reason having non-parseable arguments needs a separate code?

I think there is a value in being able to differentiate between _"something is wrong with an app"_ vs _"user provided incorrect input"_.

**Comment by djmitche** [comment]
> The reason is if someone is writing a script wrapping TC

I don't want people to do this.  The CLI is meant for human users and its ambiguities would lead to lots of challenges around escaping.  For anything beyond the simplest scripting, people should be using the Replica API and a dedicated replica.  And "simplest scripting" is much simpler than "distinguishing errors and reacting accordingly".

> I think there is a value in being able to differentiate between "something is wrong with an app" vs "user provided incorrect input".

This seems OK, and I've already implemented it :)

I think we can plan to generally work toward having a better Error type in the replica API, as @dbr has suggested, but I won't try to further improve things here.  I'll re-draft this PR to only produce 0, 1, or 3, and update the policy document accordingly.

**Comment by djmitche** [comment]
Hm, in fact, the error returns from the Replica API are all still `anyhow::Error`, not `taskchampion::Error`.  I'll file a new issue to fix that.
