### ISSUE TITLE
More descriptive --version flag

### ISSUE THREAD

**Issue by savchenko** [taskchampion/taskchampion#241]
It would be useful to show the commit ID if TaskChampion is built from HEAD.
Currently `--version` always returns the version number. Thoughts?

**Comment by djmitche** [comment]
I'm not sure how to do that.. @dbr?  Is there a way to do so in `build.rs`?

**Comment by savchenko** [comment]
I don't speak Rust, but perhaps `git describe --tags --always` would do?

**Comment by dbr** [comment]
Somewhat cumbersome but you can set env-vars in a `build.rs` script,
https://stackoverflow.com/questions/43753491/include-git-commit-hash-as-string-into-rust-program
..which is done here:
https://github.com/taskchampion/taskchampion/pull/242

`git describe --tags` is interesting (didn't know about that), but I think probably still best to use the version Cargo package version combined with `git rev-parse --short HEAD`, otherwise the git tags could get out of sync with what is pushed to http://crates.io which would be pretty confusing
